### PR TITLE
Add string and blob support

### PR DESCRIPTION
**Pull request by NullMember**
I'm currently writing an application which requires to communicate to x32/m32 digital mixer. After several failed attempts I've figured out string and blob was not supported by godOSC. So I've implemented them in this PR.

Here is brief summary of changes I made:

# OSCClient
- Added close_socket function which closes socket if opened before
- connect_socket function calls close_socket before connecting to another socket
- Added prepare_message function. So send_message function calls it before sending new packet.
- send_message function not preparing packet itself. It calls prepare_packet for this purpose.
- prepare_packet function now supports string and blob type of osc messages.

# OSCServer
- _process function not getting first packet from buffer itself. Getting packet causes first message was not parsed by parser because of get_packet function removes the packet from peer's buffer.
- parse function now only gets packet from peer and parsing is done by parse_message function.
- parse_message function now supports string and blob type of osc messages.

# Design changes
- I liked the idea of parse_rate but instead of it I've used get_available_packet_count to parse all received packets. If this change bothers you I can revert it or we can change it according to your desire.
- Parsing logic slightly changed due to variable size of string and blob types.

Thanks for your work.

### CODE REVIEW

**Comment by dfcompose** [comment]
Thanks for your interest in the project (and your contribution as well)! I'll probably get to this over the weekend. 

- I liked the idea of parse_rate but instead of it I've used get_available_packet_count to parse all received packets. If this change bothers you I can revert it or we can change it according to your desire.

In regards to this, did you notice any performance difference? It might be better to allow people to choose one or the other if there is a meaningful performance difference. I can run some diagnostic/stress tests this weekend as well if you don't have this information available yet.

**Comment by NullMember** [comment]
I've not tested it and just assumed it's fine but could impact the godot app's performance if short bursts of messages are received since parsing is done at the frame generation stage. I've overlooked that fact. I'm new to godot and this is the first project I'm making with it. I will be glad if you have a chance to make tests.

**Comment by dfcompose** [comment]
I'll run some tests this weekend. The parser should *probably* be lightweight enough that parsing lots incoming messages all at once probably won't be a big deal, but if it has performance issues I'll include an option for both and just note that parse_rate should be used if there are performance concerns. Again I appreciate the input!

**Comment by dfcompose** [comment]
After doing some tests, it seems to be just as performant as parse_rate (if not a little more performant). I'll go ahead and merge this pull. Thanks for your contribution!

**Pull request merged**
